<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'scrm',
  'author' => 'SimpleCRM',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'SMS',
  'published_date' => '2016-08-30 11:23:27',
  'type' => 'module',
  'version' => 1472556207,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'SMS',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'scrm_SMS',
      'class' => 'scrm_SMS',
      'path' => 'modules/scrm_SMS/scrm_SMS.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/scrm_sms_scrm_partners_scrm_Partners.php',
      'to_module' => 'scrm_Partners',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/scrm_sms_scrm_partner_contacts_scrm_Partner_Contacts.php',
      'to_module' => 'scrm_Partner_Contacts',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/scrm_sms_scrm_sms_template_scrm_SMS_Template.php',
      'to_module' => 'scrm_SMS_Template',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/scrm_sms_scrm_partnersMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/scrm_sms_scrm_partner_contactsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/scrm_sms_scrm_sms_templateMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/scrm_SMS',
      'to' => 'modules/scrm_SMS',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'es_es',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'ru_ru',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_Partners.php',
      'to_module' => 'scrm_Partners',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_Partners.php',
      'to_module' => 'scrm_Partners',
      'language' => 'es_es',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_Partners.php',
      'to_module' => 'scrm_Partners',
      'language' => 'ru_ru',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'es_es',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'ru_ru',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_Partner_Contacts.php',
      'to_module' => 'scrm_Partner_Contacts',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_Partner_Contacts.php',
      'to_module' => 'scrm_Partner_Contacts',
      'language' => 'es_es',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_Partner_Contacts.php',
      'to_module' => 'scrm_Partner_Contacts',
      'language' => 'ru_ru',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'es_es',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS.php',
      'to_module' => 'scrm_SMS',
      'language' => 'ru_ru',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS_Template.php',
      'to_module' => 'scrm_SMS_Template',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS_Template.php',
      'to_module' => 'scrm_SMS_Template',
      'language' => 'es_es',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/scrm_SMS_Template.php',
      'to_module' => 'scrm_SMS_Template',
      'language' => 'ru_ru',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/scrm_sms_scrm_partners_scrm_SMS.php',
      'to_module' => 'scrm_SMS',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/scrm_sms_scrm_partners_scrm_Partners.php',
      'to_module' => 'scrm_Partners',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/scrm_sms_scrm_partner_contacts_scrm_SMS.php',
      'to_module' => 'scrm_SMS',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/scrm_sms_scrm_partner_contacts_scrm_Partner_Contacts.php',
      'to_module' => 'scrm_Partner_Contacts',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/scrm_sms_scrm_sms_template_scrm_SMS.php',
      'to_module' => 'scrm_SMS',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/scrm_sms_scrm_sms_template_scrm_SMS_Template.php',
      'to_module' => 'scrm_SMS_Template',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);