<?php 
 $GLOBALS["dictionary"]["scrm_Escalation_Matrix"]=array (
  'table' => 'scrm_escalation_matrix',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'enabled',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'scrm_escalation_matrix_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'scrm_escalation_matrix_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'scrm_escalation_matrix_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'escalated_user1_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalated User1',
      'required' => false,
      'source' => 'non-db',
      'name' => 'escalated_user1_c',
      'vname' => 'LBL_ESCALATED_USER1',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'user_id1_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'scrm_Escalation_Matrixescalated_user1_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalation_minutes_level1_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalation Time in Hours',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'escalation_minutes_level1_c',
      'vname' => 'LBL_ESCALATION_MINUTES_LEVEL1',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'escalation_minutes_level1_c_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixescalation_minutes_level1_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'user_id2_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'user_id2_c',
      'vname' => 'LBL_ESCALATED_USER2_USER_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'scrm_Escalation_Matrixuser_id2_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalated_user2_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalated User2',
      'required' => false,
      'source' => 'non-db',
      'name' => 'escalated_user2_c',
      'vname' => 'LBL_ESCALATED_USER2',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'user_id2_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'scrm_Escalation_Matrixescalated_user2_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalated_user3_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalated User3',
      'required' => false,
      'source' => 'non-db',
      'name' => 'escalated_user3_c',
      'vname' => 'LBL_ESCALATED_USER3',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'user_id3_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'scrm_Escalation_Matrixescalated_user3_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'user_id1_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'user_id1_c',
      'vname' => 'LBL_ESCALATED_USER1_USER_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'scrm_Escalation_Matrixuser_id1_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'email_template_3_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Email Template 3',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'email_template_3_c',
      'vname' => 'LBL_EMAIL_TEMPLATE_3',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'email_template_1_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixemail_template_3_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'ticket_type_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Ticket Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'ticket_type_c',
      'vname' => 'LBL_TICKET_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'case_type_dom',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Escalation_Matrixticket_type_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'agent_extra_time_in_minutes_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Agent Extra Time in Minutes',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'agent_extra_time_in_minutes_c',
      'vname' => 'LBL_AGENT_EXTRA_TIME_IN_MINUTES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Escalation_Matrixagent_extra_time_in_minutes_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'email_template_4_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Email Template 4',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'email_template_4_c',
      'vname' => 'LBL_EMAIL_TEMPLATE_4',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'email_template_1_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Escalation_Matrixemail_template_4_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalation_minutes_level4_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalation Time in Hours',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'escalation_minutes_level4_c',
      'vname' => 'LBL_ESCALATION_MINUTES_LEVEL4',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'escalation_minutes_level1_c_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Escalation_Matrixescalation_minutes_level4_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'overall_sla_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Overall SLA',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'overall_sla_c',
      'vname' => 'LBL_OVERALL_SLA',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Escalation_Matrixoverall_sla_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'teams_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Teams',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'teams_c',
      'vname' => 'LBL_TEAMS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'teams_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixteams_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'email_template_1_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Email Template 1',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'email_template_1_c',
      'vname' => 'LBL_EMAIL_TEMPLATE_1',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'email_template_1_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixemail_template_1_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'user_id3_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'user_id3_c',
      'vname' => 'LBL_ESCALATED_USER3_USER_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'scrm_Escalation_Matrixuser_id3_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'email_template_2_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Email Template 2',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'email_template_2_c',
      'vname' => 'LBL_EMAIL_TEMPLATE_2',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'email_template_1_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixemail_template_2_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalated_user4_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalated User',
      'required' => false,
      'source' => 'non-db',
      'name' => 'escalated_user4_c',
      'vname' => 'LBL_ESCALATED_USER4',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'user_id_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'scrm_Escalation_Matrixescalated_user4_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalation_level_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalation Level',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'escalation_level_c',
      'vname' => 'LBL_ESCALATION_LEVEL',
      'type' => 'multienum',
      'massupdate' => '0',
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'escalation_level_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
      'id' => 'scrm_Escalation_Matrixescalation_level_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalation_minutes_level3_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalation Time in Hours',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'escalation_minutes_level3_c',
      'vname' => 'LBL_ESCALATION_MINUTES_LEVEL3',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'escalation_minutes_level1_c_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixescalation_minutes_level3_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'user_id_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'user_id_c',
      'vname' => 'LBL_ESCALATED_USER4_USER_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'scrm_Escalation_Matrixuser_id_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'escalation_minutes_level2_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Escalation Time in Hours',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'escalation_minutes_level2_c',
      'vname' => 'LBL_ESCALATION_MINUTES_LEVEL2',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'escalation_minutes_level1_c_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'scrm_Escalation_Matrixescalation_minutes_level2_c',
      'custom_module' => 'scrm_Escalation_Matrix',
    ),
    'scrm_escalation_matrix_scrm_escalation_audit_1' => 
    array (
      'name' => 'scrm_escalation_matrix_scrm_escalation_audit_1',
      'type' => 'link',
      'relationship' => 'scrm_escalation_matrix_scrm_escalation_audit_1',
      'source' => 'non-db',
      'module' => 'scrm_Escalation_Audit',
      'bean_name' => 'scrm_Escalation_Audit',
      'side' => 'right',
      'vname' => 'LBL_SCRM_ESCALATION_MATRIX_SCRM_ESCALATION_AUDIT_1_FROM_SCRM_ESCALATION_AUDIT_TITLE',
    ),
  ),
  'relationships' => 
  array (
    'scrm_escalation_matrix_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'scrm_Escalation_Matrix',
      'rhs_table' => 'scrm_escalation_matrix',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'scrm_escalation_matrix_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'scrm_Escalation_Matrix',
      'rhs_table' => 'scrm_escalation_matrix',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'scrm_escalation_matrix_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'scrm_Escalation_Matrix',
      'rhs_table' => 'scrm_escalation_matrix',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'scrm_escalation_matrixpk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);