<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN scrm_Insurance
 */


class scrm_Insurance_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'scrm_Insurance';
	var $object_name = 'scrm_Insurance';
	var $table_name = 'scrm_insurance';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $policy_type;
		var $policy_subtype;
		var $individual_no_of_mem;
		var $sum_insured;
		var $currency_id;
		var $type;
		var $pincode;
		var $email;
		var $mobile_number;
		var $tenure;
		var $premium_amount;
		var $family_no_of_members;
		var $subtype;
		var $gender;
		var $smoker;
		var $date_of_birth;
		var $premium_frequency;
		var $premium_paying_options;
		var $annual_income;
		var $vehicle_registration_number;
		var $rto_location_city;
		var $date_of_inception;
		var $manufacturing_year;
		var $manufacturer_make;
		var $model;
		var $variant;
		var $policy_status;
		var $claim_status;
		var $insured_declared_value;
		var $addon_covers;
		var $long_term_renewable_option;
		var $existing_policy_number;
		var $previous_insurer;
		var $fuel_type;
		var $zero_depreciation;
		var $return_to_invoice;
		var $road_side_assistance;
		var $engine_protector;
		var $key_replacement;
		var $etc;
		var $registered_member_of_aai;
		var $theft_alarm;
		var $destination_travellocation;
		var $trip_start_date;
		var $trip_end_date;
		var $trip_duration;
		var $number_of_travellers;
		var $age_of_travellers;
		var $dob_of_travellers;
		var $relation_of_travellers;
		var $maximum_single_trip_duration;
		var $is_your_house_rented;
		var $age_of_the_property;
		var $type_of_property;
		var $risks_to_be_covered_for;
		var $occupation;
		var $members_of_the_family;
		var $pension_amount_per_month;
		var $city_of_residence;
		var $parents_date_of_birth;
		var $childs_date_of_birth;
		var $annual_premium;
		var $term_gender;
		var $term_tenure;
		var $term_premium_amount;
		var $two_wheeler_type;
		var $two_wheeler_premium_amount;
		var $motor_policy_type;
		var $motor_vehicle_registration_num;
		var $motor_rto_location_city;
		var $motor_date_of_inception;
		var $motor_manufacturing_year;
		var $motor_manufacturer_make;
		var $motor_model;
		var $motor_variant;
		var $motor_policy_status;
		var $motor_claim_status;
		var $motor_insured_declared_value;
		var $motor_addoncovers;
		var $motor_long_term_renewable;
		var $motor_premium_amount;
		var $travel_sum_insured;
		var $travel_premium_amount;
		var $house_sum_insured;
		var $house_premium_amount;
		var $personal_annual_income;
		var $personal_sum_insured;
		var $personal_variation;
		var $personal_premium_amount;
		var $retirment_age;
		var $retirement_premium_amount;
		var $retirement_sum_insured;
		var $retirement_date_of_birth;
		var $endowment_sum_insured;
		var $endowment_date_of_birth;
		var $endowment_city_of_residence;
		var $endowment_tenure_term;
		var $endowment_premium_amount;
		var $child_sum_insured;
		var $childplan_tenure;
		var $childplan_city_of_residence;
		var $chidplan_premium_amount;
		var $ulip_date_of_birth;
		var $ulip_city_of_residence;
		var $ulip_sum_insured;
		function scrm_Insurance_sugar(){	
		parent::Basic();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>