<?php 
 $GLOBALS["dictionary"]["scrm_Products"]=array (
  'table' => 'scrm_products',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'enabled',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'scrm_products_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'scrm_products_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'scrm_products_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'no_of_attempts_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'No. of Attempts',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'no_of_attempts_c',
      'vname' => 'LBL_NO_OF_ATTEMPTS',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
      'id' => 'scrm_Productsno_of_attempts_c',
      'custom_module' => 'scrm_Products',
    ),
    'payment_type_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Payment Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'payment_type_c',
      'vname' => 'LBL_PAYMENT_TYPE',
      'type' => 'dynamicenum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'payment_type_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'parentenum' => 'product_interest_c',
      'id' => 'scrm_Productspayment_type_c',
      'custom_module' => 'scrm_Products',
    ),
    'opportunity_horizon_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Opportunity Horizon',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'opportunity_horizon_c',
      'vname' => 'LBL_OPPORTUNITY_HORIZON',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'scrm_Productsopportunity_horizon_c',
      'custom_module' => 'scrm_Products',
    ),
    'next_call_planning_date_c' => 
    array (
      'inline_edit' => '1',
      'options' => 'date_range_search_dom',
      'labelValue' => 'Next Call Planning Date',
      'enable_range_search' => '1',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'next_call_planning_date_c',
      'vname' => 'LBL_NEXT_CALL_PLANNING_DATE',
      'type' => 'datetimecombo',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'dbType' => 'datetime',
      'id' => 'scrm_Productsnext_call_planning_date_c',
      'custom_module' => 'scrm_Products',
    ),
    'next_call_planning_comments_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Next Call Planning Comments',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'next_call_planning_comments_c',
      'vname' => 'LBL_NEXT_CALL_PLANNING_COMMENTS',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'scrm_Productsnext_call_planning_comments_c',
      'custom_module' => 'scrm_Products',
    ),
    'source_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Source',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'source_c',
      'vname' => 'LBL_SOURCE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Productssource_c',
      'custom_module' => 'scrm_Products',
    ),
    'product_interest_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Product Interest',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'product_interest_c',
      'vname' => 'LBL_PRODUCT_INTEREST',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'product_interest_c_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Productsproduct_interest_c',
      'custom_module' => 'scrm_Products',
    ),
    'investment_behaviour_segment_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Investment Behaviour Segment',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'investment_behaviour_segment_c',
      'vname' => 'LBL_INVESTMENT_BEHAVIOUR_SEGMENT',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'investment_behaviour_segment_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Productsinvestment_behaviour_segment_c',
      'custom_module' => 'scrm_Products',
    ),
    'currency_id' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
      'id' => 'scrm_Productscurrency_id',
      'custom_module' => 'scrm_Products',
    ),
    'opportunity_value_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Opportunity Value',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'opportunity_value_c',
      'vname' => 'LBL_OPPORTUNITY_VALUE',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'scrm_Productsopportunity_value_c',
      'custom_module' => 'scrm_Products',
    ),
    'campaign_type_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Campaign Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'campaign_type_c',
      'vname' => 'LBL_CAMPAIGN_TYPE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Productscampaign_type_c',
      'custom_module' => 'scrm_Products',
    ),
    'product_sub_type_interest_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Product Sub Type Interest',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'product_sub_type_interest_c',
      'vname' => 'LBL_PRODUCT_SUB_TYPE_INTEREST',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'sub_product_interest_c_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Productsproduct_sub_type_interest_c',
      'custom_module' => 'scrm_Products',
    ),
    'sales_stage_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Sales Stage',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'sales_stage_c',
      'vname' => 'LBL_SALES_STAGE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'User',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'sales_stage_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Productssales_stage_c',
      'custom_module' => 'scrm_Products',
    ),
    'comment_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Comment',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'comment_c',
      'vname' => 'LBL_COMMENT',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'scrm_Productscomment_c',
      'custom_module' => 'scrm_Products',
    ),
    'utm_campaign_id_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'UTM Campaign Id',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'utm_campaign_id_c',
      'vname' => 'LBL_UTM_CAMPAIGN_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Productsutm_campaign_id_c',
      'custom_module' => 'scrm_Products',
    ),
    'disposition_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Disposition',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'disposition_c',
      'vname' => 'LBL_DISPOSITION',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'disposition_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'scrm_Productsdisposition_c',
      'custom_module' => 'scrm_Products',
    ),
    'contacts_scrm_products_1' => 
    array (
      'name' => 'contacts_scrm_products_1',
      'type' => 'link',
      'relationship' => 'contacts_scrm_products_1',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'vname' => 'LBL_CONTACTS_SCRM_PRODUCTS_1_FROM_CONTACTS_TITLE',
      'id_name' => 'contacts_scrm_products_1contacts_ida',
    ),
    'contacts_scrm_products_1_name' => 
    array (
      'name' => 'contacts_scrm_products_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_CONTACTS_SCRM_PRODUCTS_1_FROM_CONTACTS_TITLE',
      'save' => true,
      'id_name' => 'contacts_scrm_products_1contacts_ida',
      'link' => 'contacts_scrm_products_1',
      'table' => 'contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'db_concat_fields' => 
      array (
        0 => 'first_name',
        1 => 'last_name',
      ),
    ),
    'contacts_scrm_products_1contacts_ida' => 
    array (
      'name' => 'contacts_scrm_products_1contacts_ida',
      'type' => 'link',
      'relationship' => 'contacts_scrm_products_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_CONTACTS_SCRM_PRODUCTS_1_FROM_SCRM_PRODUCTS_TITLE',
    ),
    'scrm_products_activities_1_calls' => 
    array (
      'name' => 'scrm_products_activities_1_calls',
      'type' => 'link',
      'relationship' => 'scrm_products_activities_1_calls',
      'source' => 'non-db',
      'module' => 'Calls',
      'bean_name' => 'Call',
      'vname' => 'LBL_SCRM_PRODUCTS_ACTIVITIES_1_CALLS_FROM_CALLS_TITLE',
    ),
    'scrm_products_activities_1_meetings' => 
    array (
      'name' => 'scrm_products_activities_1_meetings',
      'type' => 'link',
      'relationship' => 'scrm_products_activities_1_meetings',
      'source' => 'non-db',
      'module' => 'Meetings',
      'bean_name' => 'Meeting',
      'vname' => 'LBL_SCRM_PRODUCTS_ACTIVITIES_1_MEETINGS_FROM_MEETINGS_TITLE',
    ),
    'scrm_products_activities_1_notes' => 
    array (
      'name' => 'scrm_products_activities_1_notes',
      'type' => 'link',
      'relationship' => 'scrm_products_activities_1_notes',
      'source' => 'non-db',
      'module' => 'Notes',
      'bean_name' => 'Note',
      'vname' => 'LBL_SCRM_PRODUCTS_ACTIVITIES_1_NOTES_FROM_NOTES_TITLE',
    ),
    'scrm_products_activities_1_tasks' => 
    array (
      'name' => 'scrm_products_activities_1_tasks',
      'type' => 'link',
      'relationship' => 'scrm_products_activities_1_tasks',
      'source' => 'non-db',
      'module' => 'Tasks',
      'bean_name' => 'Task',
      'vname' => 'LBL_SCRM_PRODUCTS_ACTIVITIES_1_TASKS_FROM_TASKS_TITLE',
    ),
    'scrm_products_activities_1_emails' => 
    array (
      'name' => 'scrm_products_activities_1_emails',
      'type' => 'link',
      'relationship' => 'scrm_products_activities_1_emails',
      'source' => 'non-db',
      'module' => 'Emails',
      'bean_name' => 'Email',
      'vname' => 'LBL_SCRM_PRODUCTS_ACTIVITIES_1_EMAILS_FROM_EMAILS_TITLE',
    ),
    'partner_name_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Partner Name',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'partner_name_c',
      'vname' => 'LBL_PARTNER_NAME',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Productspartner_name_c',
      'custom_module' => 'scrm_Products',
    ),
    'partner_comments_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Partner Comments',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'partner_comments_c',
      'vname' => 'LBL_PARTNER_COMMENTS_C',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'scrm_Productspartner_comments_c',
      'custom_module' => 'scrm_Products',
    ),
    'assistant_id_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Assistant ID',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'assistant_id_c',
      'vname' => 'LBL_ASSISTANT_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'scrm_Productsassistant_id_c',
      'custom_module' => 'scrm_Products',
    ),
    'user_allocation_date_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'User Allocation Date',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'user_allocation_date_c',
      'vname' => 'LBL_USER_ALLOCATION_DATE',
      'type' => 'datetimecombo',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'dbType' => 'datetime',
      'id' => 'scrm_Productsuser_allocation_date_c',
      'custom_module' => 'scrm_Products',
    ),
  ),
  'relationships' => 
  array (
    'scrm_products_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'scrm_Products',
      'rhs_table' => 'scrm_products',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'scrm_products_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'scrm_Products',
      'rhs_table' => 'scrm_products',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'scrm_products_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'scrm_Products',
      'rhs_table' => 'scrm_products',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'scrm_productspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);